/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedDevIndexRouteImport } from './routes/_authenticated/dev.index'
import { Route as AuthenticatedDevTodosRouteImport } from './routes/_authenticated/dev.todos'
import { Route as AuthenticatedDevProductsRouteImport } from './routes/_authenticated/dev.products'
import { Route as AuthenticatedDevAdminsRouteImport } from './routes/_authenticated/dev.admins'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevIndexRoute = AuthenticatedDevIndexRouteImport.update({
  id: '/dev/',
  path: '/dev/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevTodosRoute = AuthenticatedDevTodosRouteImport.update({
  id: '/dev/todos',
  path: '/dev/todos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDevProductsRoute =
  AuthenticatedDevProductsRouteImport.update({
    id: '/dev/products',
    path: '/dev/products',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDevAdminsRoute = AuthenticatedDevAdminsRouteImport.update({
  id: '/dev/admins',
  path: '/dev/admins',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/dev/admins': typeof AuthenticatedDevAdminsRoute
  '/dev/products': typeof AuthenticatedDevProductsRoute
  '/dev/todos': typeof AuthenticatedDevTodosRoute
  '/dev/': typeof AuthenticatedDevIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/dev/admins': typeof AuthenticatedDevAdminsRoute
  '/dev/products': typeof AuthenticatedDevProductsRoute
  '/dev/todos': typeof AuthenticatedDevTodosRoute
  '/dev': typeof AuthenticatedDevIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/product/$id': typeof ProductIdRoute
  '/_authenticated/dev/admins': typeof AuthenticatedDevAdminsRoute
  '/_authenticated/dev/products': typeof AuthenticatedDevProductsRoute
  '/_authenticated/dev/todos': typeof AuthenticatedDevTodosRoute
  '/_authenticated/dev/': typeof AuthenticatedDevIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/profile'
    | '/product/$id'
    | '/dev/admins'
    | '/dev/products'
    | '/dev/todos'
    | '/dev/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/profile'
    | '/product/$id'
    | '/dev/admins'
    | '/dev/products'
    | '/dev/todos'
    | '/dev'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/contact'
    | '/sitemap.xml'
    | '/_authenticated/profile'
    | '/product/$id'
    | '/_authenticated/dev/admins'
    | '/_authenticated/dev/products'
    | '/_authenticated/dev/todos'
    | '/_authenticated/dev/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/': {
      id: '/_authenticated/dev/'
      path: '/dev'
      fullPath: '/dev/'
      preLoaderRoute: typeof AuthenticatedDevIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/todos': {
      id: '/_authenticated/dev/todos'
      path: '/dev/todos'
      fullPath: '/dev/todos'
      preLoaderRoute: typeof AuthenticatedDevTodosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/products': {
      id: '/_authenticated/dev/products'
      path: '/dev/products'
      fullPath: '/dev/products'
      preLoaderRoute: typeof AuthenticatedDevProductsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dev/admins': {
      id: '/_authenticated/dev/admins'
      path: '/dev/admins'
      fullPath: '/dev/admins'
      preLoaderRoute: typeof AuthenticatedDevAdminsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedDevAdminsRoute: typeof AuthenticatedDevAdminsRoute
  AuthenticatedDevProductsRoute: typeof AuthenticatedDevProductsRoute
  AuthenticatedDevTodosRoute: typeof AuthenticatedDevTodosRoute
  AuthenticatedDevIndexRoute: typeof AuthenticatedDevIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedDevAdminsRoute: AuthenticatedDevAdminsRoute,
  AuthenticatedDevProductsRoute: AuthenticatedDevProductsRoute,
  AuthenticatedDevTodosRoute: AuthenticatedDevTodosRoute,
  AuthenticatedDevIndexRoute: AuthenticatedDevIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
